include: package:lints/recommended.yaml

analyzer:
  errors:
    # @JsonKey on freezed constructor params is valid - freezed generates the fields
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    avoid_print: true
